# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NeuralActivityCubic',
                'doc_host': 'https://Indoc-Research.github.io',
                'git_url': 'https://github.com/Indoc-Research/NeuralActivityCubic',
                'lib_path': 'NeuralActivityCubic'},
  'syms': {'NeuralActivityCubic.core': {'NeuralActivityCubic.core.foo': ('core.html#foo', 'NeuralActivityCubic/core.py')}}}
