# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_api.ipynb.

# %% auto 0
__all__ = ['run_analysis']

# %% ../nbs/08_api.ipynb 2
from .datamodels import Config
from .model import Model

def run_analysis(config: Config):
    """
    Run analysis.

    Args:
        config (Config): Configuration for analysis.
    """
    model = Model()
    model.create_analysis_jobs(config)
    model.run_analysis(config)
