name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: fastai/workflows/nbdev-ci@master
        with: 
          version: 3.11
